"""empty message

Revision ID: 26efd111d61f
Revises: 943fcbcea0ae
Create Date: 2025-09-02 10:14:29.506045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26efd111d61f'
down_revision = '943fcbcea0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('signature_status')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
