"""empty message

Revision ID: 65839d3ecb08
Revises: 34f75d6faf40
Create Date: 2025-08-14 15:37:31.093318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65839d3ecb08'
down_revision = '34f75d6faf40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
