"""empty message

Revision ID: 922409fea9df
Revises: 6fc4e37d1493
Create Date: 2025-09-05 09:25:33.940750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922409fea9df'
down_revision = '6fc4e37d1493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_pin'))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_pin'), ['pin'], unique=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
