"""empty message

Revision ID: 9eebc04759d2
Revises: e8b60f64a067
Create Date: 2025-08-14 15:09:28.663019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eebc04759d2'
down_revision = 'e8b60f64a067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('start_datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('admission_date')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('end_datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
