"""Adiciona campo manager à tabela unit

Revision ID: d2c026652bf7
Revises: e5057d0d5487
Create Date: 2025-08-29 13:10:39.553509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2c026652bf7'
down_revision = 'e5057d0d5487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chamados')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    op.drop_table('usuarios')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('manager')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('senha', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('unidade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('chamados',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_usuario', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('solicitante', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('prioridade', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('localidade', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=False),
    sa.Column('setor', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('data_criacao', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'Pendente'"), nullable=True),
    sa.Column('responsavel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('solucao', mysql.TEXT(), nullable=True),
    sa.Column('anexo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('paused', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('total_attendance_time', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('deadline_time', mysql.DATETIME(), nullable=True),
    sa.Column('alert_sent', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
