"""Adicionar coluna weekday à tabela activity

Revision ID: e5057d0d5487
Revises: 3057b64e4368
Create Date: 2025-08-16 02:27:04.554539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5057d0d5487'
down_revision = '3057b64e4368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekday', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('weekday')

    # ### end Alembic commands ###
