"""Add department and phone to Employee, project and location to Activity

Revision ID: e8b60f64a067
Revises: 91ab8973b45d
Create Date: 2025-08-14 14:19:38.397743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8b60f64a067'
down_revision = '91ab8973b45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjustment_request')
    op.drop_table('time_record')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('department')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location')
        batch_op.drop_column('project')

    op.create_table('time_record',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock_in', mysql.DATETIME(), nullable=True),
    sa.Column('clock_out', mysql.DATETIME(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('clock_in_lat', mysql.FLOAT(), nullable=True),
    sa.Column('clock_in_long', mysql.FLOAT(), nullable=True),
    sa.Column('clock_out_lat', mysql.FLOAT(), nullable=True),
    sa.Column('clock_out_long', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('adjustment_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('new_time', mysql.DATETIME(), nullable=False),
    sa.Column('explanation', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
