"""Adicionar colunas de geolocalização à tabela time_record

Revision ID: f36500da895f
Revises: 
Create Date: 2025-08-13 09:58:48.096697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36500da895f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_in_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_in_long', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clock_out_long', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('clock_out_long')
        batch_op.drop_column('clock_out_lat')
        batch_op.drop_column('clock_in_long')
        batch_op.drop_column('clock_in_lat')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
